# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_calendar2', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
