# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_calendar2', '0003_jurisdiction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
